server:
  port: 0

spring:
  application:
    name: store-account
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/polite_transaction_account}
    username: ${DATABASE_USERNAME:polite_transaction_account}
    password: ${DATABASE_PASSWORD:polite_transaction_account2}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: account
  jpa:
    properties:
      hibernate:
        default_schema: account

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}